### PR TITLE
modify setting for terminal renderer

### PR DESCRIPTION
**Pull request by zhou-pj**
I created a separate PR to address the changes needed for terminal rendering syntax. So far I only find one that need to change.

On the other note, I think we can also use this PR to decide on whether we should commit to use the name `terminal_renderer` or `text` and unify the mixed use of `text` and `terminal` across the changes before we update the PR to merge to mistune.

### CODE REVIEW

**Review by csadorf — APPROVED** [review]
@zhou-pj My original intention was to regenerate the markdown file as much as possible, which is why I called it "text" and used `**` instead of ANSI mark-up for bold rendering etc. Should we maybe just implement both variants? Shouldn't be too much work at this point, should it?

**Comment by zhou-pj** [comment]
@csadorf Just want to make sure I understand correctly, you mean just make both a text and terminal format mith minor difference like I did in my last commit? If so I think we can merge this PR as well and request the mistune maintainer again once you are both good with this. @csadorf @vyasr

**Review by csadorf — COMMENTED** [review]
Would it make sense to inherit `TerminalRenderer` from `TextRenderer` and only override the functions that are different?

**Comment by vyasr** [comment]
What are the exact differences between the two variants? Just whether we include formatting markup? If so, then the inheritance relationship seems sensible.

**Comment by zhou-pj** [comment]
> What are the exact differences between the two variants? Just whether we include formatting markup? If so, then the inheritance relationship seems sensible.

@vyasr yes terminal renderer have a few terminal specific markup. I changed the terminal one to inherit from text now.

**Comment by vyasr** [comment]
The changes look pretty clean here. @csadorf once you merge I can take point on reaching out to the mistune maintainer again if you'd like.

**Review by csadorf — APPROVED** [review]

**Comment by vyasr** [comment]
@csadorf @zhou-pj  it looks like you're still using f-strings, which are a Python 3.6 feature. The CI for mistune is currently failing on a syntax error because it apparently still tests Python 2.7. You will need to use string formatting to avoid this, then hopefully we should be set.

**Comment by csadorf** [comment]
@vyasr Let's forget about merging upstream and just develop this fork for our purposes for now. We can always merge at some later point.

**Comment by vyasr** [comment]
OK, in that case can you give signac-committers write access? We will need to vendor this fork as part of the signac-flow package for the foreseeable future if we go that route.

**Pull request merged**
